//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopping_online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedback
    {
        public int feetback_id { get; set; }
        public string feetback_content { get; set; }
        public double feetback_ratting { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> account_id { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual product product { get; set; }
    }
}
