//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopping_online.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Project_SU22Entities : DbContext
    {
        public Project_SU22Entities()
            : base("name=Project_SU22Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
            //Database.SetInitializer<demoEntities>(null);
            //modelBuilder.Entity<Account>().ToTable("Accounts");
            //modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();

        }

        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Function> Functions { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Role_function> Role_function { get; set; }
        public IEnumerable<object> Account { get; internal set; }
    }
}
