//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopping_online.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class blog
    {
        public int blog_id { get; set; }
        public string blog_title { get; set; }
        public string blog_author { get; set; }
        public string blog_descriptions { get; set; }
        public System.DateTime blog_createdate { get; set; }
        public string blog_createby { get; set; }
        public string blog_images { get; set; }
        public System.DateTime blog_modifydate { get; set; }
        public string blog_modifyby { get; set; }
        public string blog_detail { get; set; }
    }
}
