//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopping_online
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int id { get; set; }
        public string title { get; set; }
        public string author { get; set; }
        public string descriptions { get; set; }
        public System.DateTime createdate { get; set; }
        public string createby { get; set; }
        public string images { get; set; }
        public System.DateTime modifydate { get; set; }
        public string modifyby { get; set; }
        public string detail { get; set; }
        public int category_id { get; set; }
    
        public virtual Category_blog Category_blog { get; set; }
    }
}
