//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopping_online
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category_blog
    {
        public Category_blog()
        {
            this.Blogs = new HashSet<Blog>();
        }
    
        public int id { get; set; }
        public string category_name { get; set; }
    
        public virtual ICollection<Blog> Blogs { get; set; }
    }
}
