//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopping_online
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Order_Details = new HashSet<Order_Details>();
        }
    
        public int id { get; set; }
        public Nullable<int> account_id { get; set; }
        public string note { get; set; }
        public int status_id { get; set; }
        public double total_money { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int shipping_id { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<Order_Details> Order_Details { get; set; }
        public virtual Shipping Shipping { get; set; }
        public virtual Status_order Status_order { get; set; }
    }
}
