//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopping_online
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Feedbacks = new HashSet<Feedback>();
            this.Order_Details = new HashSet<Order_Details>();
            this.Productsizes = new HashSet<Productsize>();
        }
    
        public int product_id { get; set; }
        public string image_product { get; set; }
        public string product_name { get; set; }
        public double product_price { get; set; }
        public int color_id { get; set; }
        public int product_quantity { get; set; }
        public int category_id { get; set; }
        public int status_id { get; set; }
        public string product_description { get; set; }
        public string product_code { get; set; }
        public Nullable<System.DateTime> product_create_date { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Color Color { get; set; }
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual ICollection<Order_Details> Order_Details { get; set; }
        public virtual Status_product Status_product { get; set; }
        public virtual ICollection<Productsize> Productsizes { get; set; }
    }
}
