//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing.Tests.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int account_id { get; set; }
        public string account_username { get; set; }
        public string account_password { get; set; }
        public string account_email { get; set; }
        public string account_name { get; set; }
        public string account_phone { get; set; }
        public string account_address { get; set; }
        public int account_role_id { get; set; }
        public Nullable<bool> account_gender { get; set; }
        public bool account_status { get; set; }
        public Nullable<System.DateTime> account_createdate { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
