//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing.Tests.Content
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBContext : DbContext
    {
        public DBContext()
            : base("name=DBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Accounts { get; set; }
        public DbSet<Blog> Blogs { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Color> Colors { get; set; }
        public DbSet<Function> Functions { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<Order_Details> Order_Details { get; set; }
        public DbSet<Order_status> Order_status { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Role_function> Role_function { get; set; }
        public DbSet<shipping> shippings { get; set; }
        public DbSet<size> sizes { get; set; }
        public DbSet<Slide> Slides { get; set; }
        public DbSet<status_product> status_product { get; set; }
        public DbSet<productsize> productsizes { get; set; }
    }
}
