//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing.Tests.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_status
    {
        public Order_status()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int Order_status_id { get; set; }
        public string Order_status_status { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
