//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing.Tests.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Order_Details = new HashSet<Order_Details>();
        }
    
        public int Order_id { get; set; }
        public Nullable<int> account_id { get; set; }
        public string Order_note { get; set; }
        public int Order_status_id { get; set; }
        public double Order_total_money { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
        public int shipping_id { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Order_status Order_status { get; set; }
        public virtual shipping shipping { get; set; }
        public virtual ICollection<Order_Details> Order_Details { get; set; }
    }
}
