//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing.Tests.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.Order_Details = new HashSet<Order_Details>();
            this.productsizes = new HashSet<productsize>();
        }
    
        public int product_id { get; set; }
        public string product_name { get; set; }
        public decimal product_price { get; set; }
        public Nullable<int> color_id { get; set; }
        public int product_quantity { get; set; }
        public string product_image { get; set; }
        public Nullable<int> category_id { get; set; }
        public int status_product_id { get; set; }
        public string product_description { get; set; }
        public string product_code { get; set; }
        public System.DateTime product_create_date { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Color Color { get; set; }
        public virtual ICollection<Order_Details> Order_Details { get; set; }
        public virtual status_product status_product { get; set; }
        public virtual ICollection<productsize> productsizes { get; set; }
    }
}
