//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing.Tests.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class productsize
    {
        public Nullable<int> product_id { get; set; }
        public Nullable<int> size_id { get; set; }
        public int product_quantity { get; set; }
    
        public virtual product product { get; set; }
        public virtual size size { get; set; }
    }
}
