//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing.Tests.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class shipping
    {
        public shipping()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int shipping_id { get; set; }
        public string shipping_name { get; set; }
        public string shipping_email { get; set; }
        public string shipping_phone { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
