//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing.Tests.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class size
    {
        public size()
        {
            this.productsizes = new HashSet<productsize>();
        }
    
        public int size_id { get; set; }
        public int size_names { get; set; }
    
        public virtual ICollection<productsize> productsizes { get; set; }
    }
}
