//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopping_online.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int id { get; set; }
        public string content { get; set; }
        public double ratting { get; set; }
        public Nullable<int> product_id { get; set; }
        public int account_id { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
