//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopping_online.Context
{
    using shopping_online.Common;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Order_Details = new HashSet<Order_Details>();
        }

        public int Order_id { get; set; }
        public Nullable<int> account_id { get; set; }
        public string Order_note { get; set; }
        public int Order_status_id { get; set; }
        public double Order_total_money { get; set; }
        [DateRange("01/01/2021", ErrorMessage = "Date of Order must be between 01-01-2021 and Current Date")]
        [DisplayFormat(DataFormatString = "{0:d}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Order_Date { get; set; }
        public int shipping_id { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Order_status Order_status { get; set; }
        public virtual shipping shipping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Details> Order_Details { get; set; }
    }
}
