//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopping_online.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slide
    {
        public int slide_id { get; set; }
        public string slide_title { get; set; }
        public System.DateTime slide_createdate { get; set; }
        public string slide_createby { get; set; }
        public Nullable<System.DateTime> slide_modifydate { get; set; }
        public string slide_modifyby { get; set; }
        public string slide_imageslide { get; set; }
        public string slide_descriptions { get; set; }
        public bool slide_status_id { get; set; }
    }
}
