//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopping_online.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slide
    {
        public int id { get; set; }
        public string title { get; set; }
        public System.DateTime createdate { get; set; }
        public string createby { get; set; }
        public Nullable<System.DateTime> modifydate { get; set; }
        public string modifyby { get; set; }
        public string imageslide { get; set; }
        public string descriptions { get; set; }
    }
}
